'use client'
import type { Bounty } from '@/types'
import { formatDate, formatXLM } from '@/utils/formatters'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Calendar, ExternalLink, UserRound } from 'lucide-react'
import { useRouter } from 'next/navigation'

const labels: Record<string, string> = { created: 'Created', funded: 'Funded', linked: 'PR linked', verified: 'Verified', paid: 'Paid out', cancelled: 'Cancelled', disputed: 'Disputed' }
export function BountyCard({ bounty, onClick }: { bounty: Bounty; onClick?: (bounty: Bounty) => void }) { const router = useRouter(); const expired = bounty.deadline && Date.now() / 1000 > bounty.deadline; const claimable = bounty.status === 'linked' || bounty.status === 'verified'; const open = () => onClick ? onClick(bounty) : router.push(`/bounties/${bounty.id}`)
return <article onClick={open} className="group flex h-full cursor-pointer flex-col rounded-xl border border-zinc-800 bg-zinc-950 p-5 transition-colors hover:border-zinc-600"><div className="flex items-start justify-between gap-4"><Badge variant="outline" className="border-zinc-700 text-zinc-300">{labels[bounty.status] ?? bounty.status}</Badge>{expired && <span className="text-xs text-zinc-500">Expired</span>}</div><div className="mt-7"><p className="text-3xl font-semibold tracking-tight">{formatXLM(bounty.amount)} <span className="text-sm font-medium text-zinc-500">{bounty.token || 'XLM'}</span></p><a href={bounty.issue_url} target="_blank" rel="noreferrer" onClick={e => e.stopPropagation()} className="mt-4 block truncate text-sm font-medium text-zinc-200 hover:text-white">{bounty.issue_url.replace('https://github.com/', '')}</a></div><div className="mt-5 space-y-2 border-t border-zinc-800 pt-4 text-xs text-zinc-500"><p className="flex items-center gap-2 truncate"><UserRound className="h-3.5 w-3.5" />{bounty.creator}</p>{bounty.deadline && <p className="flex items-center gap-2"><Calendar className="h-3.5 w-3.5" />{expired ? 'Deadline passed' : `Due ${formatDate(bounty.deadline * 1000)}`}</p>}</div><div className="mt-auto flex gap-2 pt-5">{claimable && <Button size="sm" onClick={e => { e.stopPropagation(); open() }}>Claim</Button>}<Button size="sm" variant="outline" className="ml-auto" onClick={e => { e.stopPropagation(); window.open(bounty.issue_url, '_blank', 'noopener,noreferrer') }}>Issue <ExternalLink /></Button></div></article> }
