'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useWallet } from '@/contexts/WalletContext'
import { Button } from '@/components/ui/button'
import { LayoutDashboard, Award, Plus, Info, User, Wallet, LogOut } from 'lucide-react'

const items = [{ title: 'Overview', url: '/', icon: LayoutDashboard }, { title: 'Bounties', url: '/bounties', icon: Award }, { title: 'Create bounty', url: '/bounties/create', icon: Plus }, { title: 'Profile', url: '/profile', icon: User }, { title: 'About', url: '/about', icon: Info }]
export function Sidebar() { const pathname = usePathname(); const { connected, connecting, connect, disconnect, address, demoMode, enableDemoMode } = useWallet(); const short = address ? `${address.slice(0, 6)}…${address.slice(-4)}` : ''
return <aside className="sticky top-0 hidden h-screen w-64 shrink-0 flex-col border-r border-zinc-800 bg-[#050505] lg:flex"><div className="flex h-16 items-center border-b border-zinc-800 px-5"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-7 w-7 place-items-center rounded-md bg-zinc-100 text-sm text-black">C</span>CodeBounty</Link></div><nav className="flex-1 space-y-1 p-3">{items.map(({title,url,icon:Icon}) => <Link key={url} href={url} className={`flex h-9 items-center gap-3 rounded-md px-3 text-sm transition-colors ${pathname === url ? 'bg-zinc-100 text-zinc-950' : 'text-zinc-400 hover:bg-zinc-900 hover:text-zinc-100'}`}><Icon className="h-4 w-4" />{title}</Link>)}</nav><div className="border-t border-zinc-800 p-3">{connected ? <div className="space-y-2"><p className="truncate px-2 text-xs text-zinc-400">{demoMode ? 'Demo mode' : short}</p><Button variant="outline" size="sm" className="w-full" onClick={disconnect}><LogOut /> Disconnect</Button></div> : <div className="space-y-2"><Button className="w-full" size="sm" onClick={() => connect()} disabled={connecting}><Wallet />{connecting ? 'Connecting' : 'Connect wallet'}</Button><button className="w-full text-xs text-zinc-500 hover:text-zinc-200" onClick={enableDemoMode}>Try demo mode</button></div>}</div></aside> }
