[workspace]
resolver = "2"
members = [
    "bounty-registry",
    "merge-verifier",
]

[workspace.dependencies]
soroban-sdk = "22.0.6"
stellar-sdk = "22.0.6"
getrandom = { version = "0.2", features = ["soroban"] }
sha2 = { version = "0.10", default-features = false }
hedgy = "0.1.0-beta.2"

[workspace.metadata]
soroban = "22.0.6"